'use client';

import { useRef, useState } from 'react';
import { AnimatePresence, motion, useInView } from 'framer-motion';
import { X, ZoomIn } from 'lucide-react';
import { gallery, galleryCategories, gallerySectionContent } from '@/data/gallery';

const placeholderColors = ['from-blue-400 to-blue-600', 'from-red-400 to-red-600', 'from-green-400 to-green-600', 'from-amber-400 to-amber-600', 'from-purple-400 to-purple-600', 'from-teal-400 to-teal-600'];
function PlaceholderImage({ index, alt, className = '' }: { index: number; alt: string; className?: string }) { return <div className={`bg-gradient-to-br ${placeholderColors[index % placeholderColors.length]} ${className}`} role="img" aria-label={alt}><div className="flex h-full w-full items-center justify-center text-white/60"><svg className="h-12 w-12" fill="none" viewBox="0 0 24 24" stroke="currentColor" aria-hidden="true"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1} d="M4 16l4.586-4.586a2 2 0 012.828 0L16 16m-2-2l1.586-1.586a2 2 0 012.828 0L20 14m-6-6h.01M6 20h12a2 2 0 002-2H6a2 2 0 00-2 2v12a2 2 0 002 2z" /></svg></div></div>; }

export function GallerySection() { const [filter, setFilter] = useState('all'); const [lightbox, setLightbox] = useState<number | null>(null); const ref = useRef<HTMLDivElement>(null); const inView = useInView(ref, { once: true, margin: '-80px' }); const filtered = filter === 'all' ? gallery : gallery.filter((item) => item.category === filter); return <section id="gallery" className="bg-surface py-16 sm:py-24" aria-label="Photo gallery"><div ref={ref} className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8"><div className="mb-8"><p className="mb-2 text-sm font-semibold uppercase tracking-widest text-brand-service">{gallerySectionContent.eyebrow}</p><h2 className="text-3xl font-bold tracking-tight sm:text-4xl">{gallerySectionContent.title}</h2><p className="mt-2 text-muted-foreground">{gallerySectionContent.description}</p></div><div className="mb-8 flex flex-wrap gap-2" role="tablist">{galleryCategories.map((category) => <button key={category.value} type="button" role="tab" aria-selected={filter === category.value} onClick={() => setFilter(category.value)} className={`rounded-lg px-3 py-1.5 text-sm font-medium ${filter === category.value ? 'bg-primary text-primary-foreground' : 'bg-muted text-muted-foreground hover:text-foreground'}`}>{category.label}</button>)}</div><div className="columns-1 gap-4 sm:columns-2 lg:columns-3">{filtered.map((item, index) => <motion.div key={item.id} initial={{ opacity: 0, y: 16 }} animate={inView ? { opacity: 1, y: 0 } : {}} className="mb-4 break-inside-avoid"><button type="button" onClick={() => setLightbox(index)} className="group relative block w-full overflow-hidden rounded-xl" aria-label={`View: ${item.alt}`}><PlaceholderImage index={index} alt={item.alt} className={index % 3 === 0 ? 'aspect-[4/3]' : index % 3 === 1 ? 'aspect-square' : 'aspect-[3/4]'} /><ZoomIn className="absolute right-2 top-2 h-4 w-4 text-white opacity-0 group-hover:opacity-100" /><span className="absolute bottom-0 left-0 right-0 bg-gradient-to-t from-black/60 px-3 pb-3 pt-8 text-left text-xs text-white">{item.caption}</span></button></motion.div>)}</div></div><AnimatePresence>{lightbox !== null && filtered[lightbox] && <motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }} className="fixed inset-0 z-[100] flex items-center justify-center bg-black/90 p-4" onClick={() => setLightbox(null)} role="dialog" aria-modal="true" aria-label="Image lightbox"><button type="button" onClick={() => setLightbox(null)} className="absolute right-4 top-4 text-white" aria-label="Close lightbox"><X /></button><div className="max-w-4xl overflow-hidden rounded-xl" onClick={(event) => event.stopPropagation()}><PlaceholderImage index={lightbox} alt={filtered[lightbox].alt} className="aspect-video w-full" /><p className="bg-white p-4 text-sm text-gray-700">{filtered[lightbox].caption}</p></div></motion.div>}</AnimatePresence></section>; }
