'use client';

import { useRef, useState } from 'react';
import { motion, useInView } from 'framer-motion';
import { ArrowRight, BookOpen, Droplets, Heart, Leaf, Shirt, Sparkles } from 'lucide-react';
import { events } from '@/data/events';
import { initiatives, initiativesSectionContent } from '@/data/initiatives';
import type { InitiativeRecord } from '@/types/content';

const iconMap: Record<string, typeof Leaf> = { 'plantation-drive': Leaf, 'blood-donation': Droplets, 'swachh-bharat': Sparkles, 'medical-camp': Heart, 'education-support': BookOpen, 'clothing-distribution': Shirt };
function InitiativeCard({ initiative, index, inView, onSelect }: { initiative: InitiativeRecord; index: number; inView: boolean; onSelect: () => void }) { const Icon = iconMap[initiative.slug] ?? Leaf; const eventCount = events.filter((event) => event.initiativeSlug === initiative.slug).length; return <motion.button type="button" onClick={onSelect} initial={{ opacity: 0, y: 24 }} animate={inView ? { opacity: 1, y: 0 } : {}} transition={{ duration: 0.4, delay: index * 0.08 }} className="group flex flex-col rounded-2xl border bg-card p-6 text-left hover:-translate-y-1 hover:shadow-medium"><div className="mb-4 flex h-12 w-12 items-center justify-center rounded-xl bg-primary/10 text-primary"><Icon className="h-6 w-6" /></div><h3 className="mb-2 text-lg font-semibold group-hover:text-primary">{initiative.title}</h3><p className="mb-4 flex-1 text-sm leading-relaxed text-muted-foreground">{initiative.purpose}</p><div className="flex items-center justify-between"><span className="text-xs text-muted-foreground">{eventCount} event{eventCount === 1 ? '' : 's'}</span><span className="inline-flex items-center gap-1 text-sm font-medium text-primary">Learn more <ArrowRight className="h-3.5 w-3.5" /></span></div></motion.button>; }
export function InitiativesSection() { const [selectedSlug, setSelectedSlug] = useState<string | null>(null); const ref = useRef<HTMLDivElement>(null); const inView = useInView(ref, { once: true, margin: '-80px' }); const selected = initiatives.find((initiative) => initiative.slug === selectedSlug); const relatedEvents = events.filter((event) => event.initiativeSlug === selectedSlug); return <section id="initiatives" className="bg-surface py-16 sm:py-24" aria-label="Our initiatives"><div ref={ref} className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8"><div className="mb-12 text-center"><p className="mb-2 text-sm font-semibold uppercase tracking-widest text-brand-service">{initiativesSectionContent.eyebrow}</p><h2 className="text-3xl font-bold tracking-tight sm:text-4xl">{initiativesSectionContent.title}</h2><p className="mx-auto mt-3 max-w-2xl text-muted-foreground">{initiativesSectionContent.description}</p></div><div className="grid gap-6 sm:grid-cols-2 lg:grid-cols-3">{initiatives.map((initiative, index) => <InitiativeCard key={initiative.slug} initiative={initiative} index={index} inView={inView} onSelect={() => setSelectedSlug(initiative.slug)} />)}</div>{selected && <motion.article initial={{ opacity: 0, height: 0 }} animate={{ opacity: 1, height: 'auto' }} className="mt-12 overflow-hidden rounded-2xl border bg-card p-8 shadow-soft"><button type="button" onClick={() => setSelectedSlug(null)} className="mb-4 text-sm text-muted-foreground hover:text-foreground">← Back to all initiatives</button><h3 className="mb-2 text-2xl font-bold">{selected.title}</h3><p className="mb-4 text-sm text-muted-foreground">{selected.period}</p><p className="mb-6 leading-relaxed text-muted-foreground">{selected.context}</p><div className="grid gap-6 sm:grid-cols-2"><div><h4 className="mb-2 font-semibold">Key Activities</h4><p className="text-sm leading-relaxed text-muted-foreground">{selected.activities}</p></div><div><h4 className="mb-2 font-semibold">Evidence & Outcomes</h4><p className="text-sm leading-relaxed text-muted-foreground">{selected.evidence}</p></div></div>{relatedEvents.length > 0 && <div className="mt-6"><h4 className="mb-3 font-semibold">Related Events</h4>{relatedEvents.map((event) => <a key={event.slug} href={`#event-${event.slug}`} className="block rounded-lg border p-3 text-sm hover:bg-muted"><span className="font-medium">{event.title}</span></a>)}</div>}</motion.article>}</div></section>; }
